/********************************************************************************
** Form generated from reading UI file 'DATPlayerUI.ui'
**
** Created: Tue Jun 16 03:16:31 2015
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GUIFRONTEND_H
#define UI_GUIFRONTEND_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDateEdit>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListView>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QGroupBox *grp0;
    QGroupBox *grp3;
    QListView *list_annotation;
    QListView *list_selected_annotation;
    QLabel *label_3;
    QListView *list_event;
    QListView *list_selected_event;
    QPushButton *btn_d_annotation;
    QLabel *label_6;
    QPushButton *btn_s_annotation;
    QPushButton *btn_s_event;
    QLabel *label_4;
    QPushButton *btn_d_event;
    QCheckBox *chk_annotation;
    QCheckBox *chk_search;
    QLineEdit *txt_search;
    QLabel *label_5;
    QListView *list_ai;
    QPushButton *btn_s_ai;
    QListView *list_selected_ai;
    QPushButton *btn_d_ai;
    QLabel *label_13;
    QGroupBox *grp1;
    QLabel *label_25;
    QListView *list_project;
    QPushButton *btn_d_project;
    QPushButton *btn_s_project;
    QListView *list_selected_project;
    QLabel *label_28;
    QLabel *label_8;
    QLabel *label_7;
    QListView *list_selected_feature;
    QPushButton *btn_d_feature;
    QPushButton *btn_s_feature;
    QListView *list_feature;
    QLabel *label_29;
    QLabel *label_27;
    QPushButton *btn_d_vin;
    QListView *list_selected_vin;
    QListView *list_vin;
    QPushButton *btn_s_vin;
    QCheckBox *chk_date;
    QLabel *label;
    QDateEdit *dateEdit_2;
    QDateEdit *dateEdit;
    QLabel *label_2;
    QCheckBox *chk_fcm_event;
    QCheckBox *chk_eyeq_event;
    QCheckBox *chk_user_event;
    QCheckBox *chk_radar;
    QLabel *lbl_user;
    QGroupBox *grp2;
    QPushButton *btn_d_roadtype;
    QListView *list_road;
    QListView *list_weather;
    QPushButton *btn_d_daytype;
    QPushButton *btn_s_roadtype;
    QLabel *label_15;
    QListView *list_selected_day;
    QPushButton *btn_s_daytype;
    QLabel *label_17;
    QLabel *label_12;
    QPushButton *btn_s_weathertype;
    QLabel *label_16;
    QListView *list_day;
    QListView *list_selected_road;
    QLabel *label_18;
    QLabel *label_14;
    QListView *list_selected_weather;
    QPushButton *btn_d_weathertype;
    QLabel *label_9;
    QLabel *label_10;
    QListView *list_event_status;
    QPushButton *btn_d_event_status;
    QListView *list_selected_event_status;
    QPushButton *btn_s_event_status;
    QGroupBox *grp4;
    QPushButton *btn_make;
    QListView *list_clip_list;
    QLabel *lbl_clip;
    QGroupBox *grp_pwchange;
    QLineEdit *txt_change_id;
    QLineEdit *txt_cur_pw;
    QLineEdit *txt_change_pw;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QPushButton *btn_change;
    QPushButton *btn_change_cancel;
    QLineEdit *txt_change_pw2;
    QLabel *label_26;
    QGroupBox *grp_login;
    QLineEdit *txt_loginid;
    QLineEdit *txt_loginpw;
    QPushButton *btn_login;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *btn_change_pw;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QString::fromUtf8("Form"));
        Form->resize(1273, 886);
        grp0 = new QGroupBox(Form);
        grp0->setObjectName(QString::fromUtf8("grp0"));
        grp0->setGeometry(QRect(10, -10, 1231, 571));
        grp3 = new QGroupBox(grp0);
        grp3->setObjectName(QString::fromUtf8("grp3"));
        grp3->setEnabled(true);
        grp3->setGeometry(QRect(10, 240, 1211, 171));
        list_annotation = new QListView(grp3);
        list_annotation->setObjectName(QString::fromUtf8("list_annotation"));
        list_annotation->setGeometry(QRect(430, 45, 170, 121));
        list_annotation->setSelectionMode(QAbstractItemView::MultiSelection);
        list_selected_annotation = new QListView(grp3);
        list_selected_annotation->setObjectName(QString::fromUtf8("list_selected_annotation"));
        list_selected_annotation->setGeometry(QRect(650, 45, 170, 121));
        list_selected_annotation->setSelectionMode(QAbstractItemView::MultiSelection);
        label_3 = new QLabel(grp3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(90, 20, 41, 16));
        label_3->setLayoutDirection(Qt::LeftToRight);
        list_event = new QListView(grp3);
        list_event->setObjectName(QString::fromUtf8("list_event"));
        list_event->setGeometry(QRect(20, 45, 170, 121));
        list_event->setSelectionMode(QAbstractItemView::MultiSelection);
        list_selected_event = new QListView(grp3);
        list_selected_event->setObjectName(QString::fromUtf8("list_selected_event"));
        list_selected_event->setGeometry(QRect(240, 45, 170, 121));
        list_selected_event->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_annotation = new QPushButton(grp3);
        btn_d_annotation->setObjectName(QString::fromUtf8("btn_d_annotation"));
        btn_d_annotation->setGeometry(QRect(610, 105, 31, 23));
        label_6 = new QLabel(grp3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(670, 20, 161, 20));
        btn_s_annotation = new QPushButton(grp3);
        btn_s_annotation->setObjectName(QString::fromUtf8("btn_s_annotation"));
        btn_s_annotation->setGeometry(QRect(610, 75, 31, 23));
        btn_s_event = new QPushButton(grp3);
        btn_s_event->setObjectName(QString::fromUtf8("btn_s_event"));
        btn_s_event->setGeometry(QRect(200, 75, 31, 23));
        label_4 = new QLabel(grp3);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(280, 20, 81, 16));
        btn_d_event = new QPushButton(grp3);
        btn_d_event->setObjectName(QString::fromUtf8("btn_d_event"));
        btn_d_event->setGeometry(QRect(200, 105, 31, 23));
        chk_annotation = new QCheckBox(grp3);
        chk_annotation->setObjectName(QString::fromUtf8("chk_annotation"));
        chk_annotation->setGeometry(QRect(500, 20, 151, 17));
        chk_search = new QCheckBox(grp3);
        chk_search->setObjectName(QString::fromUtf8("chk_search"));
        chk_search->setGeometry(QRect(425, 20, 71, 17));
        chk_search->setChecked(true);
        txt_search = new QLineEdit(grp3);
        txt_search->setObjectName(QString::fromUtf8("txt_search"));
        txt_search->setGeometry(QRect(499, 19, 321, 20));
        label_5 = new QLabel(grp3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(1040, 20, 151, 16));
        list_ai = new QListView(grp3);
        list_ai->setObjectName(QString::fromUtf8("list_ai"));
        list_ai->setGeometry(QRect(842, 45, 151, 121));
        list_ai->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_s_ai = new QPushButton(grp3);
        btn_s_ai->setObjectName(QString::fromUtf8("btn_s_ai"));
        btn_s_ai->setGeometry(QRect(1000, 80, 31, 23));
        list_selected_ai = new QListView(grp3);
        list_selected_ai->setObjectName(QString::fromUtf8("list_selected_ai"));
        list_selected_ai->setGeometry(QRect(1040, 44, 151, 121));
        list_selected_ai->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_ai = new QPushButton(grp3);
        btn_d_ai->setObjectName(QString::fromUtf8("btn_d_ai"));
        btn_d_ai->setGeometry(QRect(1000, 110, 31, 23));
        label_13 = new QLabel(grp3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(860, 21, 111, 16));
        label_13->setLayoutDirection(Qt::LeftToRight);
        grp1 = new QGroupBox(grp0);
        grp1->setObjectName(QString::fromUtf8("grp1"));
        grp1->setGeometry(QRect(10, 70, 1211, 161));
        label_25 = new QLabel(grp1);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(90, 10, 46, 13));
        list_project = new QListView(grp1);
        list_project->setObjectName(QString::fromUtf8("list_project"));
        list_project->setGeometry(QRect(20, 30, 171, 111));
        list_project->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_project = new QPushButton(grp1);
        btn_d_project->setObjectName(QString::fromUtf8("btn_d_project"));
        btn_d_project->setGeometry(QRect(200, 90, 31, 23));
        btn_s_project = new QPushButton(grp1);
        btn_s_project->setObjectName(QString::fromUtf8("btn_s_project"));
        btn_s_project->setGeometry(QRect(200, 60, 31, 23));
        list_selected_project = new QListView(grp1);
        list_selected_project->setObjectName(QString::fromUtf8("list_selected_project"));
        list_selected_project->setGeometry(QRect(240, 30, 171, 111));
        list_selected_project->setSelectionMode(QAbstractItemView::MultiSelection);
        label_28 = new QLabel(grp1);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(290, 10, 81, 16));
        label_8 = new QLabel(grp1);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(690, 10, 91, 16));
        label_8->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        label_7 = new QLabel(grp1);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(500, 10, 41, 16));
        list_selected_feature = new QListView(grp1);
        list_selected_feature->setObjectName(QString::fromUtf8("list_selected_feature"));
        list_selected_feature->setGeometry(QRect(650, 27, 171, 111));
        list_selected_feature->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_feature = new QPushButton(grp1);
        btn_d_feature->setObjectName(QString::fromUtf8("btn_d_feature"));
        btn_d_feature->setGeometry(QRect(610, 87, 31, 23));
        btn_s_feature = new QPushButton(grp1);
        btn_s_feature->setObjectName(QString::fromUtf8("btn_s_feature"));
        btn_s_feature->setGeometry(QRect(610, 57, 31, 23));
        list_feature = new QListView(grp1);
        list_feature->setObjectName(QString::fromUtf8("list_feature"));
        list_feature->setGeometry(QRect(430, 27, 171, 111));
        list_feature->setSelectionMode(QAbstractItemView::MultiSelection);
        label_29 = new QLabel(grp1);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(1090, 10, 71, 16));
        label_27 = new QLabel(grp1);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(909, 10, 21, 16));
        btn_d_vin = new QPushButton(grp1);
        btn_d_vin->setObjectName(QString::fromUtf8("btn_d_vin"));
        btn_d_vin->setGeometry(QRect(1005, 90, 31, 23));
        list_selected_vin = new QListView(grp1);
        list_selected_vin->setObjectName(QString::fromUtf8("list_selected_vin"));
        list_selected_vin->setGeometry(QRect(1046, 30, 141, 111));
        list_selected_vin->setSelectionMode(QAbstractItemView::MultiSelection);
        list_vin = new QListView(grp1);
        list_vin->setObjectName(QString::fromUtf8("list_vin"));
        list_vin->setGeometry(QRect(843, 30, 151, 111));
        list_vin->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_s_vin = new QPushButton(grp1);
        btn_s_vin->setObjectName(QString::fromUtf8("btn_s_vin"));
        btn_s_vin->setGeometry(QRect(1005, 60, 31, 23));
        chk_date = new QCheckBox(grp0);
        chk_date->setObjectName(QString::fromUtf8("chk_date"));
        chk_date->setGeometry(QRect(21, 43, 101, 17));
        chk_date->setCheckable(true);
        chk_date->setChecked(true);
        label = new QLabel(grp0);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(100, 46, 46, 13));
        label->setAlignment(Qt::AlignCenter);
        dateEdit_2 = new QDateEdit(grp0);
        dateEdit_2->setObjectName(QString::fromUtf8("dateEdit_2"));
        dateEdit_2->setEnabled(false);
        dateEdit_2->setGeometry(QRect(330, 36, 121, 31));
        dateEdit_2->setCurrentSection(QDateTimeEdit::YearSection);
        dateEdit_2->setCalendarPopup(true);
        dateEdit = new QDateEdit(grp0);
        dateEdit->setObjectName(QString::fromUtf8("dateEdit"));
        dateEdit->setEnabled(false);
        dateEdit->setGeometry(QRect(150, 37, 121, 31));
        dateEdit->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        dateEdit->setCurrentSection(QDateTimeEdit::YearSection);
        dateEdit->setCalendarPopup(true);
        label_2 = new QLabel(grp0);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(280, 46, 46, 13));
        label_2->setAlignment(Qt::AlignCenter);
        chk_fcm_event = new QCheckBox(grp0);
        chk_fcm_event->setObjectName(QString::fromUtf8("chk_fcm_event"));
        chk_fcm_event->setGeometry(QRect(530, 40, 81, 17));
        chk_eyeq_event = new QCheckBox(grp0);
        chk_eyeq_event->setObjectName(QString::fromUtf8("chk_eyeq_event"));
        chk_eyeq_event->setGeometry(QRect(620, 40, 81, 17));
        chk_user_event = new QCheckBox(grp0);
        chk_user_event->setObjectName(QString::fromUtf8("chk_user_event"));
        chk_user_event->setGeometry(QRect(710, 40, 91, 17));
        chk_radar = new QCheckBox(grp0);
        chk_radar->setObjectName(QString::fromUtf8("chk_radar"));
        chk_radar->setGeometry(QRect(790, 40, 91, 17));
        lbl_user = new QLabel(grp0);
        lbl_user->setObjectName(QString::fromUtf8("lbl_user"));
        lbl_user->setGeometry(QRect(20, 10, 181, 16));
        grp2 = new QGroupBox(grp0);
        grp2->setObjectName(QString::fromUtf8("grp2"));
        grp2->setGeometry(QRect(10, 420, 1211, 141));
        btn_d_roadtype = new QPushButton(grp2);
        btn_d_roadtype->setObjectName(QString::fromUtf8("btn_d_roadtype"));
        btn_d_roadtype->setGeometry(QRect(676, 90, 31, 23));
        list_road = new QListView(grp2);
        list_road->setObjectName(QString::fromUtf8("list_road"));
        list_road->setGeometry(QRect(576, 30, 91, 101));
        list_road->setSelectionMode(QAbstractItemView::MultiSelection);
        list_weather = new QListView(grp2);
        list_weather->setObjectName(QString::fromUtf8("list_weather"));
        list_weather->setGeometry(QRect(300, 30, 91, 101));
        list_weather->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_daytype = new QPushButton(grp2);
        btn_d_daytype->setObjectName(QString::fromUtf8("btn_d_daytype"));
        btn_d_daytype->setGeometry(QRect(120, 90, 31, 23));
        btn_s_roadtype = new QPushButton(grp2);
        btn_s_roadtype->setObjectName(QString::fromUtf8("btn_s_roadtype"));
        btn_s_roadtype->setGeometry(QRect(676, 60, 31, 23));
        label_15 = new QLabel(grp2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(430, 10, 121, 16));
        list_selected_day = new QListView(grp2);
        list_selected_day->setObjectName(QString::fromUtf8("list_selected_day"));
        list_selected_day->setGeometry(QRect(160, 30, 91, 101));
        list_selected_day->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_s_daytype = new QPushButton(grp2);
        btn_s_daytype->setObjectName(QString::fromUtf8("btn_s_daytype"));
        btn_s_daytype->setGeometry(QRect(120, 60, 31, 23));
        label_17 = new QLabel(grp2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(596, 10, 51, 16));
        label_12 = new QLabel(grp2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(40, 10, 51, 16));
        btn_s_weathertype = new QPushButton(grp2);
        btn_s_weathertype->setObjectName(QString::fromUtf8("btn_s_weathertype"));
        btn_s_weathertype->setGeometry(QRect(400, 60, 31, 23));
        label_16 = new QLabel(grp2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(310, 10, 71, 16));
        list_day = new QListView(grp2);
        list_day->setObjectName(QString::fromUtf8("list_day"));
        list_day->setGeometry(QRect(20, 30, 91, 101));
        list_day->setSelectionMode(QAbstractItemView::MultiSelection);
        list_selected_road = new QListView(grp2);
        list_selected_road->setObjectName(QString::fromUtf8("list_selected_road"));
        list_selected_road->setGeometry(QRect(716, 30, 91, 101));
        list_selected_road->setSelectionMode(QAbstractItemView::MultiSelection);
        label_18 = new QLabel(grp2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(716, 10, 101, 16));
        label_14 = new QLabel(grp2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(160, 10, 101, 16));
        list_selected_weather = new QListView(grp2);
        list_selected_weather->setObjectName(QString::fromUtf8("list_selected_weather"));
        list_selected_weather->setGeometry(QRect(440, 30, 91, 101));
        list_selected_weather->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_weathertype = new QPushButton(grp2);
        btn_d_weathertype->setObjectName(QString::fromUtf8("btn_d_weathertype"));
        btn_d_weathertype->setGeometry(QRect(400, 90, 31, 23));
        label_9 = new QLabel(grp2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(1062, 7, 111, 16));
        label_9->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        label_10 = new QLabel(grp2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(887, 5, 71, 16));
        list_event_status = new QListView(grp2);
        list_event_status->setObjectName(QString::fromUtf8("list_event_status"));
        list_event_status->setGeometry(QRect(842, 21, 151, 111));
        list_event_status->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_d_event_status = new QPushButton(grp2);
        btn_d_event_status->setObjectName(QString::fromUtf8("btn_d_event_status"));
        btn_d_event_status->setGeometry(QRect(1000, 84, 31, 23));
        list_selected_event_status = new QListView(grp2);
        list_selected_event_status->setObjectName(QString::fromUtf8("list_selected_event_status"));
        list_selected_event_status->setGeometry(QRect(1040, 24, 151, 111));
        list_selected_event_status->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_s_event_status = new QPushButton(grp2);
        btn_s_event_status->setObjectName(QString::fromUtf8("btn_s_event_status"));
        btn_s_event_status->setGeometry(QRect(1000, 54, 31, 23));
        label_4->raise();
        list_event->raise();
        btn_d_event->raise();
        list_selected_event->raise();
        btn_s_event->raise();
        label_3->raise();
        btn_d_roadtype->raise();
        list_road->raise();
        list_weather->raise();
        btn_d_daytype->raise();
        btn_s_roadtype->raise();
        label_15->raise();
        list_selected_day->raise();
        btn_s_daytype->raise();
        label_17->raise();
        label_12->raise();
        btn_s_weathertype->raise();
        label_16->raise();
        list_day->raise();
        list_selected_road->raise();
        label_18->raise();
        label_14->raise();
        list_selected_weather->raise();
        btn_d_weathertype->raise();
        label_9->raise();
        label_10->raise();
        list_event_status->raise();
        btn_d_event_status->raise();
        list_selected_event_status->raise();
        btn_s_event_status->raise();
        grp4 = new QGroupBox(Form);
        grp4->setObjectName(QString::fromUtf8("grp4"));
        grp4->setGeometry(QRect(10, 570, 1251, 111));
        btn_make = new QPushButton(grp4);
        btn_make->setObjectName(QString::fromUtf8("btn_make"));
        btn_make->setGeometry(QRect(440, 10, 91, 91));
        list_clip_list = new QListView(grp4);
        list_clip_list->setObjectName(QString::fromUtf8("list_clip_list"));
        list_clip_list->setEnabled(true);
        list_clip_list->setGeometry(QRect(30, 10, 391, 91));
        lbl_clip = new QLabel(grp4);
        lbl_clip->setObjectName(QString::fromUtf8("lbl_clip"));
        lbl_clip->setGeometry(QRect(540, 80, 381, 16));
        grp_pwchange = new QGroupBox(Form);
        grp_pwchange->setObjectName(QString::fromUtf8("grp_pwchange"));
        grp_pwchange->setGeometry(QRect(480, 350, 231, 181));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(170, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(212, 255, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(85, 127, 127, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(113, 170, 170, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        grp_pwchange->setPalette(palette);
        grp_pwchange->setAutoFillBackground(true);
        txt_change_id = new QLineEdit(grp_pwchange);
        txt_change_id->setObjectName(QString::fromUtf8("txt_change_id"));
        txt_change_id->setGeometry(QRect(90, 20, 113, 20));
        txt_cur_pw = new QLineEdit(grp_pwchange);
        txt_cur_pw->setObjectName(QString::fromUtf8("txt_cur_pw"));
        txt_cur_pw->setGeometry(QRect(90, 50, 113, 20));
        txt_change_pw = new QLineEdit(grp_pwchange);
        txt_change_pw->setObjectName(QString::fromUtf8("txt_change_pw"));
        txt_change_pw->setGeometry(QRect(90, 80, 113, 20));
        label_20 = new QLabel(grp_pwchange);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 25, 46, 13));
        label_21 = new QLabel(grp_pwchange);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 54, 61, 16));
        label_22 = new QLabel(grp_pwchange);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 85, 46, 13));
        label_22->setFrameShape(QFrame::NoFrame);
        label_22->setFrameShadow(QFrame::Plain);
        btn_change = new QPushButton(grp_pwchange);
        btn_change->setObjectName(QString::fromUtf8("btn_change"));
        btn_change->setGeometry(QRect(110, 150, 91, 23));
        btn_change_cancel = new QPushButton(grp_pwchange);
        btn_change_cancel->setObjectName(QString::fromUtf8("btn_change_cancel"));
        btn_change_cancel->setGeometry(QRect(16, 150, 91, 23));
        txt_change_pw2 = new QLineEdit(grp_pwchange);
        txt_change_pw2->setObjectName(QString::fromUtf8("txt_change_pw2"));
        txt_change_pw2->setGeometry(QRect(90, 110, 113, 20));
        label_26 = new QLabel(grp_pwchange);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(21, 114, 61, 16));
        grp_login = new QGroupBox(Form);
        grp_login->setObjectName(QString::fromUtf8("grp_login"));
        grp_login->setGeometry(QRect(480, 230, 231, 121));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        QBrush brush7(QColor(85, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush7);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        grp_login->setPalette(palette1);
        grp_login->setAutoFillBackground(true);
        txt_loginid = new QLineEdit(grp_login);
        txt_loginid->setObjectName(QString::fromUtf8("txt_loginid"));
        txt_loginid->setGeometry(QRect(90, 20, 113, 20));
        txt_loginpw = new QLineEdit(grp_login);
        txt_loginpw->setObjectName(QString::fromUtf8("txt_loginpw"));
        txt_loginpw->setGeometry(QRect(90, 50, 113, 20));
        btn_login = new QPushButton(grp_login);
        btn_login->setObjectName(QString::fromUtf8("btn_login"));
        btn_login->setGeometry(QRect(90, 80, 111, 23));
        label_23 = new QLabel(grp_login);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(20, 25, 46, 13));
        label_24 = new QLabel(grp_login);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 53, 46, 13));
        btn_change_pw = new QPushButton(grp_login);
        btn_change_pw->setObjectName(QString::fromUtf8("btn_change_pw"));
        btn_change_pw->setGeometry(QRect(10, 80, 75, 23));
        QWidget::setTabOrder(list_selected_annotation, btn_make);
        QWidget::setTabOrder(btn_make, list_clip_list);
        QWidget::setTabOrder(list_clip_list, btn_d_feature);
        QWidget::setTabOrder(btn_d_feature, btn_s_feature);
        QWidget::setTabOrder(btn_s_feature, list_selected_feature);
        QWidget::setTabOrder(list_selected_feature, list_feature);
        QWidget::setTabOrder(list_feature, dateEdit);
        QWidget::setTabOrder(dateEdit, dateEdit_2);
        QWidget::setTabOrder(dateEdit_2, chk_user_event);
        QWidget::setTabOrder(chk_user_event, chk_eyeq_event);
        QWidget::setTabOrder(chk_eyeq_event, chk_fcm_event);
        QWidget::setTabOrder(chk_fcm_event, chk_date);
        QWidget::setTabOrder(chk_date, list_annotation);
        QWidget::setTabOrder(list_annotation, list_event);
        QWidget::setTabOrder(list_event, list_selected_event);
        QWidget::setTabOrder(list_selected_event, btn_d_annotation);
        QWidget::setTabOrder(btn_d_annotation, btn_s_annotation);
        QWidget::setTabOrder(btn_s_annotation, btn_s_event);
        QWidget::setTabOrder(btn_s_event, btn_d_event);
        QWidget::setTabOrder(btn_d_event, chk_annotation);
        QWidget::setTabOrder(chk_annotation, txt_loginid);
        QWidget::setTabOrder(txt_loginid, txt_loginpw);
        QWidget::setTabOrder(txt_loginpw, btn_login);
        QWidget::setTabOrder(btn_login, btn_change_pw);
        QWidget::setTabOrder(btn_change_pw, txt_change_id);
        QWidget::setTabOrder(txt_change_id, txt_cur_pw);
        QWidget::setTabOrder(txt_cur_pw, txt_change_pw);
        QWidget::setTabOrder(txt_change_pw, txt_change_pw2);
        QWidget::setTabOrder(txt_change_pw2, btn_change);
        QWidget::setTabOrder(btn_change, btn_change_cancel);
        QWidget::setTabOrder(btn_change_cancel, chk_radar);
        QWidget::setTabOrder(chk_radar, chk_search);
        QWidget::setTabOrder(chk_search, txt_search);

        retranslateUi(Form);

        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QApplication::translate("Form", "Form", 0, QApplication::UnicodeUTF8));
        grp0->setTitle(QString());
        grp3->setTitle(QString());
        label_3->setText(QApplication::translate("Form", "Events", 0, QApplication::UnicodeUTF8));
        btn_d_annotation->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Form", "Selected Predefined Annotation", 0, QApplication::UnicodeUTF8));
        btn_s_annotation->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        btn_s_event->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Form", "Selected Events", 0, QApplication::UnicodeUTF8));
        btn_d_event->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        chk_annotation->setText(QApplication::translate("Form", "By Predefined Annotation?", 0, QApplication::UnicodeUTF8));
        chk_search->setText(QApplication::translate("Form", "By Search?", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Form", "Selected Additional Information", 0, QApplication::UnicodeUTF8));
        btn_s_ai->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        btn_d_ai->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("Form", "Additional Information", 0, QApplication::UnicodeUTF8));
        grp1->setTitle(QString());
        label_25->setText(QApplication::translate("Form", "Project", 0, QApplication::UnicodeUTF8));
        btn_d_project->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_s_project->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("Form", "Selected Project", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Form", "Selected Feature", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Form", "Feature", 0, QApplication::UnicodeUTF8));
        btn_d_feature->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_s_feature->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("Form", "Selected VIN", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("Form", "VIN", 0, QApplication::UnicodeUTF8));
        btn_d_vin->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_s_vin->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        chk_date->setText(QApplication::translate("Form", "All Date?", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Form", "START", 0, QApplication::UnicodeUTF8));
        dateEdit_2->setDisplayFormat(QApplication::translate("Form", "yyyy/MM/dd", 0, QApplication::UnicodeUTF8));
        dateEdit->setDisplayFormat(QApplication::translate("Form", "yyyy/MM/dd", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Form", "END", 0, QApplication::UnicodeUTF8));
        chk_fcm_event->setText(QApplication::translate("Form", "FCM_Event", 0, QApplication::UnicodeUTF8));
        chk_eyeq_event->setText(QApplication::translate("Form", "EyeQ_Event", 0, QApplication::UnicodeUTF8));
        chk_user_event->setText(QApplication::translate("Form", "User_Event", 0, QApplication::UnicodeUTF8));
        chk_radar->setText(QApplication::translate("Form", "Radar_Event", 0, QApplication::UnicodeUTF8));
        lbl_user->setText(QString());
        grp2->setTitle(QString());
        btn_d_roadtype->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_d_daytype->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_s_roadtype->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Form", "Selected Weather Type", 0, QApplication::UnicodeUTF8));
        btn_s_daytype->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Form", "Road Type", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Form", "Day Type", 0, QApplication::UnicodeUTF8));
        btn_s_weathertype->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Form", "Weather Type", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Form", "Selected Road Type", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Form", "Selected Day Type", 0, QApplication::UnicodeUTF8));
        btn_d_weathertype->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Form", "Selected Event Status", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Form", "Event Status", 0, QApplication::UnicodeUTF8));
        btn_d_event_status->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_s_event_status->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        grp4->setTitle(QString());
        btn_make->setText(QApplication::translate("Form", "Generate \n"
" Play List", 0, QApplication::UnicodeUTF8));
        lbl_clip->setText(QString());
        grp_pwchange->setTitle(QApplication::translate("Form", "PW Change", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Form", "ID", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Form", "Current PW", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Form", "New PW", 0, QApplication::UnicodeUTF8));
        btn_change->setText(QApplication::translate("Form", "Change", 0, QApplication::UnicodeUTF8));
        btn_change_cancel->setText(QApplication::translate("Form", "Cancel", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("Form", "New PW", 0, QApplication::UnicodeUTF8));
        grp_login->setTitle(QApplication::translate("Form", "LOG-IN", 0, QApplication::UnicodeUTF8));
        btn_login->setText(QApplication::translate("Form", "Log-In", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("Form", "ID", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("Form", "Password", 0, QApplication::UnicodeUTF8));
        btn_change_pw->setText(QApplication::translate("Form", "PW Change", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GUIFRONTEND_H
